# -*- coding: utf-8 -*-
"""export_litert.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/186XoAUX3VxcxHLOI6rKxXchyPqd13-Fg
"""

!pip install ultralytics

from ultralytics import YOLO

# Load a YOLO26 model
model = YOLO("/content/best.pt")

# Export the model to LiteRT format
model.export(format="litert")  # creates 'yolo26n.tflite'